### ISSUE TITLE
Update the Lithuanian constituency to the European Parliament

### ISSUE THREAD

**Issue by filipvanlaenen** [filipvanlaenen/sapor#47]
Should be as follows:

- Tėvynės sąjunga–Lietuvos krikščionys demokratai (EPP)
- Lietuvos valstiečių ir žaliųjų sąjunga (Greens/EFA)
- **Partija tvarka ir teisingumas (*)** (Was: ECR)
- Lietuvos socialdemokratų partija (S&D)
- Liberalų Sąjūdis (RE)
- Lietuvos lenkų rinkimų akcija (ECR)
- Lietuvos Centro Partija (ECR)
- Darbo Partija (RE)
- **Lietuvos Žaliųjų Partija (Greens/EFA)** (Was: *)
- Politinė partija “Lietuvos sąrašas” (*)
- Lietuvos socialdemokratų darbo partija (S&D)
- **Laisvės partija (RE)** (Was: *)

**Comment by Vogone** [comment]
The EP groups match now. The Lietuvos centro partija has changed its name to Centro partija „Gerovės Lietuva“, but if these labels are just for internal use I am not sure how much of a priority it is for you to keep them in line with eopaod's. There the party list currently reads:

Tėvynės sąjunga – Lietuvos krikščionys demokratai           | #0080FF | TS-LKD
Lietuvos valstiečių ir žaliųjų sąjunga                      | #61A347 | LVŽS
Partija „Tvarka ir teisingumas“                             | #FFF500 | TT
Lietuvos socialdemokratų partija                            | #FF101A | LSDP 
Lietuvos Respublikos liberalų sąjūdis                       | #F29402 | LRLS
Lietuvos lenkų rinkimų akcija – Krikščioniškų šeimų sąjunga | #FF7462 | LLRA-KŠS
Centro partija „Gerovės Lietuva“                            | #74DF00 | LCP
Darbo partija                                               | #001978 | DP
Lietuvos žaliųjų partija                                    | #80BD00 | LŽP
Politinė partija „Lietuvos sąrašas“                         | #9C0000 | LS
Lietuvos socialdemokratų darbo partija                      | #FF0000 | LSDDP
Laisvės partija                                             | #E3006B | LP
